version: 2
project_name: claude-token-monitor

before:
  hooks:
    - go mod tidy

builds:
  - id: statusline
    main: ./cmd/statusline
    binary: statusline
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: statusline
    builds:
      - statusline
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "statusline_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: young1lin
    name: claude-token-monitor
  draft: false
  prerelease: auto
